required = [
 "github.com/mattn/goreman",
]

[[constraint]]
  name = "github.com/scaledata/etcd"
  branch = "release-3.3-kronos"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  # Avoid pruning projects containing needed protos.

  [[prune.project]]
    name = "github.com/gogo/protobuf"
    unused-packages = false
